#!/usr/bin/env bash

function _command_exists ()
{
  type "$1" &> /dev/null ;
}

# Load theme, if a theme was set
if [[ ! -z "${BASH_IT_THEME}" ]]; then
  # Load colors and helpers first so they can be used in base theme
  source "${DOTFILES}/themes/colours.theme.bash"
  # shellcheck source=./themes/githelpers.theme.bash
  source "${DOTFILES}/themes/githelpers.theme.bash"
  # shellcheck source=./themes/p4helpers.theme.bash
  source "${DOTFILES}/themes/p4helpers.theme.bash"
  # shellcheck source=./themes/base.theme.bash
  source "${DOTFILES}/themes/base.theme.bash"

  # coloured ls
  export LSCOLORS='Gxfxcxdxdxegedabagacad'

  # Load the theme
  if [[ -f $BASH_IT_THEME ]]; then
        source $BASH_IT_THEME
  else
        source "$DOTFILES/themes/$BASH_IT_THEME/$BASH_IT_THEME.theme.bash"
  fi

fi
