#!/usr/bin/env bash

export GOPATH=~/go

function _command_exists() {
	type "$1" &>/dev/null
}

# coloured ls
#	export LSCOLORS='Gxfxcxdxdxegedabagacad'

function _update_ps1() {
   PS1="$($GOPATH/bin/powerline-go -condensed -cwd-max-depth 3 -alternate-ssh-icon  -hostname-only-if-ssh -colorize-hostname  -error $?)"
   }
